[build]
  publish = "public"
  command = "hugo --gc --minify --themesDir themes/anatole"
  
[build.environment]
  HUGO_VERSION = "0.92.1"
  HUGO_ENV = "production"
  HUGO_THEME = "repo"

[[headers]]
  for = "/*"
    [headers.values]
      Access-Control-Allow-Origin = "*"